// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: chatpb.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_CLIENT UserRole = 0
	UserRole_ADMIN  UserRole = 1
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "CLIENT",
		1: "ADMIN",
	}
	UserRole_value = map[string]int32{
		"CLIENT": 0,
		"ADMIN":  1,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_chatpb_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_chatpb_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_chatpb_proto_rawDescGZIP(), []int{0}
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          UserRole               `protobuf:"varint,1,opt,name=role,proto3,enum=api.UserRole" json:"role,omitempty"`
	IsServer      bool                   `protobuf:"varint,2,opt,name=isServer,proto3" json:"isServer,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chatpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chatpb_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_CLIENT
}

func (x *ChatMessage) GetIsServer() bool {
	if x != nil {
		return x.IsServer
	}
	return false
}

func (x *ChatMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_chatpb_proto protoreflect.FileDescriptor

const file_chatpb_proto_rawDesc = "" +
	"\n" +
	"\fchatpb.proto\x12\x03api\"t\n" +
	"\vChatMessage\x12!\n" +
	"\x04role\x18\x01 \x01(\x0e2\r.api.UserRoleR\x04role\x12\x1a\n" +
	"\bisServer\x18\x02 \x01(\bR\bisServer\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text*!\n" +
	"\bUserRole\x12\n" +
	"\n" +
	"\x06CLIENT\x10\x00\x12\t\n" +
	"\x05ADMIN\x10\x012=\n" +
	"\vChatService\x12.\n" +
	"\x04Chat\x12\x10.api.ChatMessage\x1a\x10.api.ChatMessage(\x010\x01B\x17Z\x15example.com/myapp/apib\x06proto3"

var (
	file_chatpb_proto_rawDescOnce sync.Once
	file_chatpb_proto_rawDescData []byte
)

func file_chatpb_proto_rawDescGZIP() []byte {
	file_chatpb_proto_rawDescOnce.Do(func() {
		file_chatpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatpb_proto_rawDesc), len(file_chatpb_proto_rawDesc)))
	})
	return file_chatpb_proto_rawDescData
}

var file_chatpb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatpb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chatpb_proto_goTypes = []any{
	(UserRole)(0),       // 0: api.UserRole
	(*ChatMessage)(nil), // 1: api.ChatMessage
}
var file_chatpb_proto_depIdxs = []int32{
	0, // 0: api.ChatMessage.role:type_name -> api.UserRole
	1, // 1: api.ChatService.Chat:input_type -> api.ChatMessage
	1, // 2: api.ChatService.Chat:output_type -> api.ChatMessage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chatpb_proto_init() }
func file_chatpb_proto_init() {
	if File_chatpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatpb_proto_rawDesc), len(file_chatpb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatpb_proto_goTypes,
		DependencyIndexes: file_chatpb_proto_depIdxs,
		EnumInfos:         file_chatpb_proto_enumTypes,
		MessageInfos:      file_chatpb_proto_msgTypes,
	}.Build()
	File_chatpb_proto = out.File
	file_chatpb_proto_goTypes = nil
	file_chatpb_proto_depIdxs = nil
}
